### ISSUE TITLE
Vocal Victories (Split and Rework)

### ISSUE THREAD

**Issue by NCanney** [NCanney/NoelTestSprint#3]
- [x] Phase 1: CF to review all VV content
- [x] Phase 2: Define Programs, Courses and Modules
- [x] Phase 3: Define Learning Aim and Learning Objectives (Broken into cards at program level)
- [x] Phase 4: Content Plan (Component Level) (Broken into cards at program level)
- [x] Phase 5: Content Development (Adapt)
- [ ] Phase 6: Peer Review (From non-team members)
- [ ] Phase 7: Prepare and Send Relevant Information to Marketing and Sales
- [ ] Phase 8: Implement Peer Review Corrections and Final Quality Check
- [ ] Phase 9: Organise release of Marketing and Sales Information
- [ ] Phase 10: Upload and Release
